version: "3.9"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
      - ./gunicorn_config.py:/app/gunicorn_config.py
      - ./.cache:/home/appuser/.cache
    restart: always
